### ISSUE TITLE
Feature to add/edit items

### ISSUE THREAD

**Issue by jamkerr** [duizendnegen/sunburst-smorgasbord#11]
## Description

As a unique individual with unique relationships, I want the ability to edit or add items and categories to match the specifics of my relationships, so that I can use this tool without being confined by prior (and arbitrary) definitions.

This wish came up a lot in the intial round of feedback, either explicitly or in the form of "why is x (not) included?".

## Acceptance criteria:

- [ ] A user can add an item at any level
- [ ] A user can edit an item at any level
- [ ] A user can delete an item (and all children) at any level?

### Spreading

This should probably affect the "spreading" behavior of items at the lowest level. In a previous iteration at least, when you hid an item you would still see a gap where the item was. With potentially infinite items now, we should probably have the lowest level items always fill the entire circle. Creating a new item at that level would make each item smaller, and deleting an item at that level would make each item larger to fill the circle.

### Gaps when deleting

Currently, you can "hide" items to leave a gap in the image. But if you can delete items, why would you ever just hide them? You could delete everything that wasn't relevant to you. This would result in far fewer gaps in the final image, which _might_ affect the sunburst look (not sure though).
In any case, defining when someone should hide an item as opposed to deleting it seems important, since they're similar actions with different (visual) outcomes.

**Comment by duizendnegen** [comment]
Done, although for now without an edit mode.
