### ISSUE TITLE
Feedback: Orientation of text can be confusing

### ISSUE THREAD

**Issue by jamkerr** [duizendnegen/sunburst-smorgasbord#12]
In the first feedback round, a few people mentioned that either:
1. The orientation of the text switching within a category at 180 degrees was confusing/annoying (specific problem)
2. In general, non-horizontally oriented text is confusing/annoying (general problem)

A proposed solution to issue 2 was to be able to rotate the wheel, or interact with it in some other way that changes the text orientation.

**Comment by duizendnegen** [comment]
Addressed by rotating the wheel
