### ISSUE TITLE
Feedback: More options than binary selected/deselected

### ISSUE THREAD

**Issue by jamkerr** [duizendnegen/sunburst-smorgasbord#14]
In the first feedback round, some people mentioned that they'd appreciate a distinction between "important to have" and "like but not essential".

I've seen this done elsewhere. In a non-escalator relationship menu that I've used there were 4 levels of distinction: must have, like to have, maybe, and off limits : https://www.reddit.com/r/polyamory/comments/pwkdxp/v3_relationship_components_menu_last_update_for/
Also in the original that we based most of our content off they suggest 5 levels: yes, maybe, maybe in the future, let's talk, and definitely no : https://www.multiamory.com/podcast/339-the-smorgasbord-of-relationships

How could we represent something like this visually AND intuitively?

**Comment by duizendnegen** [comment]
Fixed with introducing a greyed out state (3 levels); should communicate still in how people can use this (it can mean maybe, or one of us, or future, or whatever people want it to mean)
